---
# tasks file for ansible_xrdp

# roles/example/tasks/debian.yml
- name: Install Packages
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
    autoclean: yes
    autoremove: yes
    #force_apt_get: yes
    #install_recommends: yes
    #update_cache: yes
  loop: "{{ xrdp_pkgs }}"
  become: yes
  when: nodename in xrdp_hosts

- name: Create Xwrapper
  become: yes
  copy:
    src: files/Xwrapper.config
    dest: /etc/X11/Xwrapper.config

- name: Flush IPTables
  become: yes
  iptables:
    flush: yes


- name: Add xrdp to groups
  become: yes
  user:
    name: "xrdp"
    groups: "{{ item }}"
  loop:
    - ssl-cert, xrdp, tty
  register: result

- name: Results
  debug:
    msg: "{{ result }}"

# Ensure a job that runs at 2 and 5 exists.
# Creates an entry like "0 5,2 * * ls -alh > /dev/null"
#- cron:
#    name: "fix rdp bugs"
#    minute: "*"
#    job: "ls -alh > /dev/null"

- name: Restart XRDP
  become: yes
  service:
    name: xrdp
    state: started
  when: nodename in xrdp_hosts

- name: Add xrdp to groups
  become: yes
  user:
    name: "xrdp"
    groups: "{{ item }}"
  loop:
    - ssl-cert
    - xrdp
    - tty
  register: result

- name: Results
  debug:
    msg: "{{ result }}"
