---
# tasks file for ansible_xrdp

# roles/example/tasks/debian.yml
- name: Install Packages
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
  loop: "{{ xrdp_pkgs }}"
  become: yes
  when: ansible_os_family == 'Debian'

- name: Add xrdp to groups
  become: yes
  user:
    name: "xrdp"
    group: "ssl-cert"
  loop:
    - ssl-cert
    - tty

- name: Flush IPTables
  iptables:
    flush: yes